// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCACjtNMMnXxHnCA-SBgpJdtc0pZ_pQTMc',
    appId: '1:366870906394:web:5245b755bc58f641e233a3',
    messagingSenderId: '366870906394',
    projectId: 'herodex3000',
    authDomain: 'herodex3000.firebaseapp.com',
    storageBucket: 'herodex3000.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxfkkSWf-UbXBeinOPOyB2_aPuq0gA5Is',
    appId: '1:366870906394:android:c3cf1e02a537de80e233a3',
    messagingSenderId: '366870906394',
    projectId: 'herodex3000',
    storageBucket: 'herodex3000.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZAyuzYMq3N7ZmI4F1o_Pblh6H8vG6VTA',
    appId: '1:366870906394:ios:e1fef64b99beacdae233a3',
    messagingSenderId: '366870906394',
    projectId: 'herodex3000',
    storageBucket: 'herodex3000.firebasestorage.app',
    iosBundleId: 'com.example.herodex3000',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZAyuzYMq3N7ZmI4F1o_Pblh6H8vG6VTA',
    appId: '1:366870906394:ios:e1fef64b99beacdae233a3',
    messagingSenderId: '366870906394',
    projectId: 'herodex3000',
    storageBucket: 'herodex3000.firebasestorage.app',
    iosBundleId: 'com.example.herodex3000',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCACjtNMMnXxHnCA-SBgpJdtc0pZ_pQTMc',
    appId: '1:366870906394:web:b08d378876e01ed1e233a3',
    messagingSenderId: '366870906394',
    projectId: 'herodex3000',
    authDomain: 'herodex3000.firebaseapp.com',
    storageBucket: 'herodex3000.firebasestorage.app',
  );

}